---
Name: app_session_gateways
After:
  - '#coresecurity'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        SessionLogMiddleware: '%$Roadblock\Gateways\SessionLogMiddleware'
