---
Name: roadblock_session
After:
  - '#coresecurity'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        SessionLogMiddleware: '%$Roadblock\Gateways\SessionLogMiddleware'
---
Name: roadblock_member
---
SilverStripe\Security\Member:
  session_regenerate_id: false
