---
Name: roadblock_session
After:
  - '#coresecurity'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        SessionLogMiddleware: '%$aSmithSummer\Roadblock\Gateways\SessionLogMiddleware'
SilverStripe\Security\Member:
  session_regenerate_id: false
SilverStripe\Security\MemberAuthenticator\MemberAuthenticator:
  extensions:
    - aSmithSummer\Roadblock\Extensions\RoadblockMemberAuthenticatorExtension
SilverStripe\Security\LoginAttempt:
  extensions:
    - aSmithSummer\Roadblock\Extensions\RoadblockLoginAttemptExtension
